// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjaySs5pK0_yXELJAaKMu3bqSzLsBsbBg',
    appId: '1:414576085975:android:35a6cedfd355f9f8f4d992',
    messagingSenderId: '414576085975',
    projectId: 'chat-app-77808',
    storageBucket: 'chat-app-77808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9swzqtW41IE0HcTgmawxlf1sWuTfk9ts',
    appId: '1:414576085975:ios:8d263b9dcbbfa8e0f4d992',
    messagingSenderId: '414576085975',
    projectId: 'chat-app-77808',
    storageBucket: 'chat-app-77808.appspot.com',
    iosClientId: '414576085975-qpjufimm5qho8i76vamfpe8cccpe2khl.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarApp',
  );
}
